<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend>
    <p>
    <div class="field company_name">
        <label for="company_name" class="label">
            <span><?php /* @escapeNotVerified */ echo __('Company Name') ?></span>
        </label>
        <div class="control">
            <input type="text" name="company_name" id="company_name" title="<?php /* @escapeNotVerified */ echo __('Company Name') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </p>
    <p>
    <div class="field fantasy_name">
        <label for="fantasy_name" class="label">
            <span><?php /* @escapeNotVerified */ echo __('Fantasy Name') ?></span>
        </label>
        <div class="control">
            <input type="text" name="fantasy_name" id="fantasy_name" title="<?php /* @escapeNotVerified */ echo __('Fantasy Name') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </p>
    <p>
    <div class="field state_registration">
        <label for="state_registration" class="label">
            <span><?php /* @escapeNotVerified */ echo __('State Registration') ?></span>
        </label>
        <div class="control">
            <input type="text" name="state_registration" id="state_registration" title="<?php /* @escapeNotVerified */ echo __('State Registration') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </p>
</fieldset>